### ISSUE TITLE
Can't monitor webapp's JVM in JBoss EAP 6.2 (Domain mode)

### ISSUE THREAD

**Issue by ranmses** [ganglia/jmxetric#34]
Hello,
For the last couple of days I've been trying to monitor all the JVM's in our JBoss system.
We have 3 working VM (CentOS 6.5) in domain mode (1 master + 2 slaves).
As I type, that's the current situation:
- Master: 2 JVM processes, 1 host controller + 1 process controller
- Slave 1 : 3 JVM processes, 1 host controller + 1 process controller + 1 webapp (deployed jar)
- Slave 2 : 3 JVM processes, 1 host controller + 1 process controller + 1 webapp (deployed jar)
There' s one jmxetric xml file for each JVM. The problem: 

   We cannot make the webapp JVM's to be monitored. The 6 others are correctly monitored. 

For each one of the xml files I uncommented the lines below:

               <mbean name="jboss.as:subsystem=web,connector=ajp" pname="ajp">
                      <attribute name="requestCount" type="int32" slope="positive"/>
               </mbean>

All JVM processes show references of oncrpc-1.0.7.jar, gmetric4j-1.0.7.jar and jmxetric-1.0.6.jar, with apparently correct configurations. Tried to increase the delay at the xml file, but no luck.

Any ideas?

Best!

**Comment by dpocock** [comment]
This Github bug tracker is only used for tracking confirmed bugs.

This looks more like a "how do I?" support request, please ask on the ganglia-general mailing list or possibly the JBoss user forum.

Two suggestions I can make:

- check you have a distinct <jvm process="something"/> for each JVM on the same host, if two JVMs are on the same host they must not use the same process name there.

- use lsof to check the JVM process to see if the jmxetric code opened a socket

**Comment by ranmses** [comment]
Ok, sorry for the wrong request.

Yes, there's one xml with a unique process name for each JVM. I already have 2 different JVM being monitored at each one of the 3 hosts.

The problem is with the third JVM, which supports a webapp from a deployed jar file.

Will check if the socket is being open, but I suppose not since there's no sign of the metric with 'telnet localhost PORT'.

Well, thank you anyway.
